[2023-02-07T09:38:35.450+0100] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2023-02-07T09:38:35.457+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:38:35.458+0100] {base_task_runner.py:69} DEBUG - Planning to run as the  user
[2023-02-07T09:38:35.460+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> from DB
[2023-02-07T09:38:35.466+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:38:35.466+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2023-02-07T09:38:35.466+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:38:35.467+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2023-02-07T09:38:35.467+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:38:35.470+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]>
[2023-02-07T09:38:35.473+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2023-02-07T09:38:35.473+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:38:35.473+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2023-02-07T09:38:35.473+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:38:35.473+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:38:35.474+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [queued]>
[2023-02-07T09:38:35.474+0100] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:38:35.474+0100] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-07T09:38:35.474+0100] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:38:35.488+0100] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_data_to_mongodb> on 2023-02-07 08:38:33.165567+00:00
[2023-02-07T09:38:35.491+0100] {standard_task_runner.py:55} INFO - Started process 2319 to run task
[2023-02-07T09:38:35.493+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dagProcessusMetier', 'load_data_to_mongodb', 'manual__2023-02-07T08:38:33.165567+00:00', '--job-id', '2586', '--raw', '--subdir', 'DAGS_FOLDER/dagProcessusMetier.py', '--cfg-path', '/tmp/tmpb3khq57q']
[2023-02-07T09:38:35.493+0100] {standard_task_runner.py:83} INFO - Job 2586: Subtask load_data_to_mongodb
[2023-02-07T09:38:35.494+0100] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f4db1454790>]
[2023-02-07T09:38:35.506+0100] {settings.py:407} DEBUG - Disposing DB connection pool (PID 2319)
[2023-02-07T09:38:35.506+0100] {settings.py:266} DEBUG - Setting up DB connection pool (PID 2319)
[2023-02-07T09:38:35.506+0100] {settings.py:339} DEBUG - settings.prepare_engine_args(): Using NullPool
[2023-02-07T09:38:35.522+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:38:35.524+0100] {task_command.py:388} INFO - Running <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [running]> on host TR.
[2023-02-07T09:38:35.525+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:38:35.540+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:38:35.541+0100] {taskinstance.py:848} DEBUG - Clearing XCom data
[2023-02-07T09:38:35.564+0100] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2023-02-07T09:38:35.567+0100] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=thomas
AIRFLOW_CTX_DAG_ID=dagProcessusMetier
AIRFLOW_CTX_TASK_ID=load_data_to_mongodb
AIRFLOW_CTX_EXECUTION_DATE=2023-02-07T08:38:33.165567+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-07T08:38:33.165567+00:00
[2023-02-07T09:38:35.568+0100] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2023-02-07T09:38:35.568+0100] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2023-02-07T09:38:35.595+0100] {logging_mixin.py:137} INFO - DÃ©but fonction!
[2023-02-07T09:38:35.646+0100] {logging_mixin.py:137} INFO - Fin lecture fichier json
[2023-02-07T09:38:40.510+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:38:40.514+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:38:45.541+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:38:45.543+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:38:50.585+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:38:50.588+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:38:55.638+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:38:55.641+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:39:00.683+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:00.686+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:39:05.697+0100] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/tr/airflow/dags/dagProcessusMetier.py", line 35, in load_data_to_mongodb
    result = db.tweets.insert_many(file_json)
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/collection.py", line 714, in insert_many
    blk.execute(write_concern, session=session)
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 513, in execute
    return self.execute_command(generator, write_concern, session)
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/bulk.py", line 390, in execute_command
    with client._tmp_session(session) as s:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
    s = self._ensure_session(session)
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 63e20e0bb4dbdafcc9430f4b, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out')>]>
[2023-02-07T09:39:05.699+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:05.702+0100] {taskinstance.py:2241} DEBUG - Task Duration set to 30.232018
[2023-02-07T09:39:05.702+0100] {taskinstance.py:1329} DEBUG - Clearing next_method and next_kwargs.
[2023-02-07T09:39:05.703+0100] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=dagProcessusMetier, task_id=load_data_to_mongodb, execution_date=20230207T083833, start_date=20230207T083835, end_date=20230207T083905
[2023-02-07T09:39:05.720+0100] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2023-02-07T09:39:05.720+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 2586 for task load_data_to_mongodb (ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 63e20e0bb4dbdafcc9430f4b, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out')>]>; 2319)
[2023-02-07T09:39:05.741+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:05.743+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:39:05.743+0100] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-07T09:39:05.754+0100] {dagrun.py:688} DEBUG - number of tis tasks for <DagRun dagProcessusMetier @ 2023-02-07 08:38:33.165567+00:00: manual__2023-02-07T08:38:33.165567+00:00, state:running, queued_at: 2023-02-07 08:38:33.178171+00:00. externally triggered: True>: 12 task(s)
[2023-02-07T09:39:05.754+0100] {dagrun.py:709} DEBUG - number of scheduleable tasks for <DagRun dagProcessusMetier @ 2023-02-07 08:38:33.165567+00:00: manual__2023-02-07T08:38:33.165567+00:00, state:running, queued_at: 2023-02-07 08:38:33.178171+00:00. externally triggered: True>: 12 task(s)
[2023-02-07T09:39:05.754+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.create_tables manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.755+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.create_tables manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'load_data_to_mongodb'}
[2023-02-07T09:39:05.755+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.create_tables manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'load_data_to_mongodb'}
[2023-02-07T09:39:05.755+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.create_tables manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.755+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_authors manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.755+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_authors manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'create_tables'}
[2023-02-07T09:39:05.755+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.get_all_authors manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'create_tables'}
[2023-02-07T09:39:05.755+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_authors manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.755+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_hashtags manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_hashtags manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'get_all_authors'}
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.get_all_hashtags manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'get_all_authors'}
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_hashtags manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'get_all_topics'}
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.get_all_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'get_all_topics'}
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_topics manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_topics manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'get_all_hashtags'}
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.get_all_topics manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'get_all_hashtags'}
[2023-02-07T09:39:05.756+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_topics manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.757+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.insert_to_datalake manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.757+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.insert_to_datalake manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'get_all_sentiment'}
[2023-02-07T09:39:05.757+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.insert_to_datalake manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'get_all_sentiment'}
[2023-02-07T09:39:05.757+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.insert_to_datalake manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.757+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.757+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [up_for_retry]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:39:05.757+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2023-02-07T08:39:05.757568+00:00 and task will be retried at 2023-02-07T08:44:05.702162+00:00.
[2023-02-07T09:39:05.757+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.load_data_to_mongodb manual__2023-02-07T08:38:33.165567+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-02-07T08:39:05.757568+00:00 and task will be retried at 2023-02-07T08:44:05.702162+00:00.
[2023-02-07T09:39:05.757+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.757+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'insert_to_datalake'}
[2023-02-07T09:39:05.758+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.top_hashtags manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'insert_to_datalake'}
[2023-02-07T09:39:05.758+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.758+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_negative_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.758+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_negative_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'top_users'}
[2023-02-07T09:39:05.758+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.top_hashtags_negative_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'top_users'}
[2023-02-07T09:39:05.758+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_negative_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.758+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_positive_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.758+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_positive_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'top_hashtags_negative_sentiment'}
[2023-02-07T09:39:05.758+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.top_hashtags_positive_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'top_hashtags_negative_sentiment'}
[2023-02-07T09:39:05.759+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_positive_sentiment manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.759+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.759+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'top_hashtags'}
[2023-02-07T09:39:05.759+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'top_hashtags'}
[2023-02-07T09:39:05.759+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.759+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_users manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:05.759+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_users manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'top_topics'}
[2023-02-07T09:39:05.759+0100] {taskinstance.py:1073} DEBUG - Dependencies not met for <TaskInstance: dagProcessusMetier.top_users manual__2023-02-07T08:38:33.165567+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'top_topics'}
[2023-02-07T09:39:05.759+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_users manual__2023-02-07T08:38:33.165567+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:05.764+0100] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
