[2023-02-07T09:11:59.967+0100] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2023-02-07T09:11:59.976+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:11:59.977+0100] {base_task_runner.py:69} DEBUG - Planning to run as the  user
[2023-02-07T09:11:59.979+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> from DB
[2023-02-07T09:11:59.985+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:11:59.985+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:11:59.985+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2023-02-07T09:11:59.985+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2023-02-07T09:11:59.985+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:11:59.988+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]>
[2023-02-07T09:11:59.988+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:11:59.988+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:11:59.992+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2023-02-07T09:11:59.992+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2023-02-07T09:11:59.992+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:11:59.992+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [queued]>
[2023-02-07T09:11:59.992+0100] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:11:59.993+0100] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-07T09:11:59.993+0100] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:12:00.008+0100] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): top_hashtags_with_positive_sentiment> on 2023-02-05 00:00:00+00:00
[2023-02-07T09:12:00.011+0100] {standard_task_runner.py:55} INFO - Started process 538 to run task
[2023-02-07T09:12:00.012+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dagProcessusMetier', 'top_hashtags_with_positive_sentiment', 'scheduled__2023-02-05T00:00:00+00:00', '--job-id', '2578', '--raw', '--subdir', 'DAGS_FOLDER/dagProcessusMetier.py', '--cfg-path', '/tmp/tmpv709wuho']
[2023-02-07T09:12:00.013+0100] {standard_task_runner.py:83} INFO - Job 2578: Subtask top_hashtags_with_positive_sentiment
[2023-02-07T09:12:00.014+0100] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7fec78554790>]
[2023-02-07T09:12:00.038+0100] {settings.py:407} DEBUG - Disposing DB connection pool (PID 538)
[2023-02-07T09:12:00.039+0100] {settings.py:266} DEBUG - Setting up DB connection pool (PID 538)
[2023-02-07T09:12:00.039+0100] {settings.py:339} DEBUG - settings.prepare_engine_args(): Using NullPool
[2023-02-07T09:12:00.060+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:12:00.062+0100] {task_command.py:388} INFO - Running <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [running]> on host TR.
[2023-02-07T09:12:00.062+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [running]> from DB
[2023-02-07T09:12:00.082+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:12:00.083+0100] {taskinstance.py:848} DEBUG - Clearing XCom data
[2023-02-07T09:12:00.107+0100] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2023-02-07T09:12:00.112+0100] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=thomas
AIRFLOW_CTX_DAG_ID=dagProcessusMetier
AIRFLOW_CTX_TASK_ID=top_hashtags_with_positive_sentiment
AIRFLOW_CTX_EXECUTION_DATE=2023-02-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-05T00:00:00+00:00
[2023-02-07T09:12:00.112+0100] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2023-02-07T09:12:00.112+0100] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2023-02-07T09:12:00.113+0100] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/tr/airflow/dags/dagProcessusMetier.py", line 324, in top_hashtags_positive_sentiment
    K = kwargs['params']['K']
KeyError: 'K'
[2023-02-07T09:12:00.113+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.top_hashtags_with_positive_sentiment scheduled__2023-02-05T00:00:00+00:00 [running]> from DB
[2023-02-07T09:12:00.115+0100] {taskinstance.py:2241} DEBUG - Task Duration set to 0.127059
[2023-02-07T09:12:00.116+0100] {taskinstance.py:1329} DEBUG - Clearing next_method and next_kwargs.
[2023-02-07T09:12:00.116+0100] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=dagProcessusMetier, task_id=top_hashtags_with_positive_sentiment, execution_date=20230205T000000, start_date=20230207T081159, end_date=20230207T081200
[2023-02-07T09:12:00.127+0100] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2023-02-07T09:12:00.127+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 2578 for task top_hashtags_with_positive_sentiment ('K'; 538)
[2023-02-07T09:12:00.146+0100] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-07T09:12:00.153+0100] {dagrun.py:688} DEBUG - number of tis tasks for <DagRun dagProcessusMetier @ 2023-02-05 00:00:00+00:00: scheduled__2023-02-05T00:00:00+00:00, state:running, queued_at: 2023-02-07 08:08:13.813279+00:00. externally triggered: False>: 0 task(s)
[2023-02-07T09:12:00.154+0100] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
